const geojson = {
  type: "FeatureCollection",
  features: [
    {
      type: "Feature",
      properties: {
        Name: "Aster Montessori School",
        Type: "Independent",
        Subtype: "Wildflower Network",
        Phone: "857-285-6916",
        Email: "info@astermontessori.org",
        Address: "883 Cambidge Street, Cambridge, MA 02141",
        Capacity: "Capacity: 20",
        Age: "Ages served: 3-6 years",
        Website: "https://www.astermontessori.org/",
        Notes: "Montessori",
        Hours: "Max Hours: M-F, 8:30am – 5:30pm",
        Enrollment: "Calendar: Academic",
        Cost: "Full-Day Annual Tuition: $21,000 (more info on website)",
        Finaid:
          "Accepts Birth to Third Grade Partnership scholarship applications",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.0915837, 42.3726934],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Capucine Montessori School",
        Type: "Independent",
        Subtype: "Wildflower Network",
        Phone: "339-707-7709",
        Email: "marion@capucinemontessori.org",
        Address: "2180 Massachusetts Ave, Cambridge, MA 02140",
        Capacity: "Capacity: 20",
        Age: "Ages served: 2.9mo-6 years",
        Website: "https://www.capucinemontessori.org/",
        Notes: "Montessori, Bilingual (English & French)",
        Hours: "Max Hours: M-Th, 8:30am – 3:00pm; F, 8:30am-12:00pm",
        Enrollment: "Calendar: Academic",
        Cost: "Full-Day Annual Tuition: $21, 500 (more info on website)",
        Finaid: "Accepts TADS financial aid application",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.1251381, 42.3925181],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Jun Zi Lan Montessori",
        Type: "Independent",
        Subtype: "Wildflower Network",
        Phone: "781-918-3260",
        Email: "jing@junzilanmontessori.org",
        Address: "88 Cambridgepark Drive, Cambridge, MA 02140",
        Capacity: "Capacity: 20",
        Age: "Ages served: 2.9-6 years",
        Website: "https://wildflowerschools.org/ma/junzilan/",
        Notes: "Montessori, Bilingual (English & Mandarin)",
        Hours: "Max Hours: M-F, 8:30am – 5:00pm",
        Enrollment: "",
        Cost: "Full-Day Annual Tuition: $26,400 (more info on website)",
        Finaid: "Need-based financial aid might be available",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.1436399, 42.3932283],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Miramelinda Montessori School",
        Type: "Independent",
        Subtype: "Wildflower Network",
        Phone: "857-829-7782",
        Email: "rlymichelle@gmail.com",
        Address: "1064 Cambridge StreetCambridge, MA 02139",
        Capacity: "Capacity: 10",
        Age: "Ages served: Toddler (15 - 33 mo)",
        Website: "https://wildflowerschools.org/ma/miramelinda/",
        Notes: "Montessori, Bilingual (English & Spanish)",
        Hours: "Max Hours: M-F, 8:30am – 3:30pm",
        Enrollment: "Calendar: Full-year",
        Cost: "",
        Finaid: "Accepts TADS financial aid application",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.0951515, 42.3728217],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Snapdragon Montessori School",
        Type: "Independent",
        Subtype: "Wildflower Network",
        Phone: "301-275-1540",
        Email: "snapdragonmontessori@gmail.com",
        Address: "1190 Cambridge Street, Cambridge, MA 02139",
        Capacity: "Capacity: 10",
        Age: "Ages served: Toddler",
        Website: "https://wildflowerschools.org/ma/snapdragon/",
        Notes: "Montessori",
        Hours: "Max Hours: M-F, 8:30am – 4:00pm",
        Enrollment: "Calendar: Academic",
        Cost: "",
        Finaid: "Accepts TADS financial aid application",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.0972282, 42.3731287],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Violeta Montessori School, Inc.",
        Type: "Independent",
        Subtype: "Wildflower Network",
        Phone: "857-600-0084",
        Email: "mardie@violeta.org",
        Address: "290 Broadway Street, Cambridge, MA 02139",
        Capacity: "Capacity: 23",
        Age: "Ages served: 2.9-6 years",
        Website: "https://www.violeta.org/",
        Notes: "Montessori, Bilingual (English & Spanish)",
        Hours: "Max Hours: M-F, 8:30am – 5:30pm",
        Enrollment: "Calendar: Academic",
        Cost: "Full-Day Annual Tuition: $21,424 (more info on website)",
        Finaid:
          "Accepts Birth to Third Grade Partnership scholarship applications",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.0983929, 42.3681666],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Wild Rose Montessori",
        Type: "Independent",
        Subtype: "Wildflower Network",
        Phone: "617-453-8110",
        Email: "admin@wildrosemontessori.org",
        Address: "2284 Massachusetts Ave, Cambridge, MA 02140",
        Capacity: "Capacity:",
        Age: "Ages served: 2.9-6 years (& 6 - 12 years)",
        Website: "https://wildflowerschools.org/ma/wildrose/",
        Notes: "Montessori",
        Hours: "Max Hours: M-F, 8:00am – 6:00pm",
        Enrollment: "Calendar: Academic",
        Cost: "",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.1276264, 42.3947754],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Wildflower Montessori",
        Type: "Independent",
        Subtype: "Wildflower Network",
        Phone: "617-721-2159",
        Email: "mary@wildflowermontessorischool.org",
        Address: "364A Broadway, Cambridge, MA 02139",
        Capacity: "Capacity: 18",
        Age: "Ages served: 3-6 years",
        Website: "https://www.wildflowermontessorischool.org/",
        Notes: "Montessori",
        Hours: "Max Hours: M-F, 9:00am – 3:00pm",
        Enrollment: "Calendar: September - end of May",
        Cost: "Full-Day Annual Tuition: $22,750",
        Finaid: "Accepts TADS financial aid application",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.1044222, 42.3705657],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Rock & Roll - East Cambridge Annex",
        Type: "Independent",
        Subtype: "Rock & Roll Daycare",
        Phone: "617-347-5612",
        Email: "tq@ecam.rockandrolldaycare.com",
        Address: "535 Cambridge Street, Cambridge, MA 02141",
        Capacity: "Capacity: 38",
        Age: "Ages served: Infant & toddler",
        Website: "https://ecam.rockandrolldaycare.com/",
        Notes: "",
        Hours: "Max Hours: M-F, 8:30am – 5:30pm",
        Enrollment: "Calendar: Full-year",
        Cost: "",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.0852003, 42.3718829],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Rock & Roll - East Cambridge Annex",
        Type: "Independent",
        Subtype: "Rock & Roll Daycare",
        Phone: "617-347-5612",
        Email: "toquyen.zorn@gmail.com",
        Address: "580 Cambridge Street, Cambridge, MA 02141",
        Capacity: "Capacity: 10",
        Age: "Ages served: Multi-age grouping",
        Website: "https://ecam.rockandrolldaycare.com/",
        Notes: "",
        Hours: "Max Hours: M-F, 8:30am – 5:30pm",
        Enrollment: "Calendar: Full-year",
        Cost: "",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.0860323, 42.3716942],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Rock & Roll - Broadway",
        Type: "Independent",
        Subtype: "Rock & Roll Daycare",
        Phone: "617-347-5612",
        Email: "toquyen.zorn@gmail.com",
        Address: "366 Broadway, Cambridge, MA 02139",
        Capacity: "Capacity: 25",
        Age: "Ages served: infant, toddler, & preschool",
        Website: "https://bway.rockandrolldaycare.com/",
        Notes: "",
        Hours: "Max Hours: M-F, 8:30am – 5:30pm",
        Enrollment: "Calendar: Full-year",
        Cost: "",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.1046607, 42.3706554],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Rock & Roll - Broadway Annex",
        Type: "Independent",
        Subtype: "Rock & Roll Daycare",
        Phone: "617-347-5612",
        Email: "toquyen.zorn@gmail.com",
        Address: "370 Broadway, Cambridge, MA 02139",
        Capacity: "Capacity: 10",
        Age: "Ages served: Preschool",
        Website: "https://bway.rockandrolldaycare.com/",
        Notes: "",
        Hours: "Max Hours: M-F, 8:30am – 5:30pm",
        Enrollment: "Calendar: Full-year",
        Cost: "",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.1047613, 42.3706514],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Rock & Roll - Central Square",
        Type: "Independent",
        Subtype: "Rock & Roll Daycare",
        Phone: "617-347-5612",
        Email: "tq@csq.rockandrolldaycare.com",
        Address: "166 Prospect Street, Cambridge, MA 02139",
        Capacity: "Capacity: 44",
        Age: "Ages served: infant, toddler, & preschool",
        Website: "https://csq.rockandrolldaycare.com/",
        Notes: "",
        Hours: "Max Hours: M-F, 8:30am – 5:30pm",
        Enrollment: "Calendar: Full-year",
        Cost: "",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.1006098, 42.3694504],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Rock & Roll - Inman Square",
        Type: "Independent",
        Subtype: "Rock & Roll Daycare",
        Phone: "617-347-5612",
        Email: "toquyen.zorn@gmail.com",
        Address: "215 Prospect Street, Cambridge, MA 02139",
        Capacity: "Capacity: 45",
        Age: "Ages served: infant, toddler, & preschool",
        Website: "https://inman.rockandrolldaycare.com/",
        Notes: "",
        Hours: "Max Hours: M-F, 8:30am – 5:30pm",
        Enrollment: "Calendar: Full-year",
        Cost: "",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.1001256, 42.3708469],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Rock & Roll - Huron Village",
        Type: "Independent",
        Subtype: "Rock & Roll Daycare",
        Phone: "508-525-3268",
        Email: "melissagarcia@rockandrolldaycare.com",
        Address: "190 Concord Ave, Cambridge, MA 02138",
        Capacity: "Capacity: 45",
        Age: "Ages served: infant, toddler, & preschool",
        Website: "https://huronvillage.rockandrolldaycare.com/",
        Notes: "",
        Hours: "Max Hours: M-F, 8:30am – 5:30pm",
        Enrollment: "Calendar: Full-year",
        Cost: "",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.1309725, 42.3822056],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Rock & Roll - Northpoint",
        Type: "Independent",
        Subtype: "Rock & Roll Daycare",
        Phone: "857-259-5211",
        Email: "courtney@csq.rockandrolldaycare.com",
        Address: "20 Child Street, Cambridge, MA 02141",
        Capacity: "",
        Age: "Ages served: infant, toddler, & preschool",
        Website: "https://northpoint.rockandrolldaycare.com/",
        Notes: "",
        Hours: "Max Hours: M-F, 8:30am – 5:30pm",
        Enrollment: "Calendar: Full-year",
        Cost: "",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.0715503, 42.3716211],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Rock & Roll - Porter Square",
        Type: "Independent",
        Subtype: "Rock & Roll Daycare",
        Phone: "617-347-5612",
        Email: "toquyen.zorn@gmail.com",
        Address: "1971 Massachusetts Ave, Cambridge, MA 02140",
        Capacity: "Capacity: 32",
        Age: "Ages served: infant, toddler, & preschool",
        Website: "https://porter.rockandrolldaycare.com/",
        Notes: "",
        Hours: "Max Hours: M-F, 8:30am – 5:30pm",
        Enrollment: "Calendar: Full-year",
        Cost: "",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.1203557, 42.3902345],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Rock & Roll - Lechmere",
        Type: "Independent",
        Subtype: "Rock & Roll Daycare",
        Phone: "617-347-5612",
        Email: "toquyen.zorn@gmail.com",
        Address: "527 Cambridge Street, Cambridge, MA 02141",
        Capacity: "Capacity: 20",
        Age: "Ages served:",
        Website: "",
        Notes: "",
        Hours: "",
        Enrollment: "",
        Cost: "",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.0850455, 42.3718127],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Preschool of the Arts - East Cambridge",
        Type: "Independent",
        Subtype: "Preschool of the Arts",
        Phone: "617-547-9189",
        Email: "elkie@cambridgepreschool.org",
        Address: "8-12 Museum Way, Cambridge, MA 02141",
        Capacity: "Capacity: 62",
        Age: "Ages served: 12 mo - 5 years ",
        Website: "https://www.cambridgepreschool.org/eastcambridge",
        Notes: "Reggio-Emilia, Jewish",
        Hours: "Max Hours: M-F, 8:00am – 6:00pm",
        Enrollment: "Calendar: Academic OR Full-year",
        Cost: "Tuition: Monthly, see website for breakdown based on age",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.071682, 42.3701088],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Preschool of the Arts - Harvard Square",
        Type: "Independent",
        Subtype: "Preschool of the Arts",
        Phone: "617-547-9189",
        Email: "elkie@cambridgepreschool.org",
        Address: "65 Banks Street, Cambridge, MA 02138",
        Capacity: "Capacity: 38",
        Age: "Ages served: 6mo  - 5 years",
        Website: "https://www.cambridgepreschool.org/harvardsquare",
        Notes: "Reggio-Emilia, Jewish",
        Hours: "Max Hours: M-F, 8:00am – 6:00pm",
        Enrollment: "Calendar: Academic OR Full-year",
        Cost: "Tuition: Monthly, see website for breakdown based on age",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.114852, 42.369095],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Preschool of the Arts - West Cambridge",
        Type: "Independent",
        Subtype: "Preschool of the Arts",
        Phone: "617-547-9189",
        Email: "office@cambridgepreschool.org",
        Address: "299 Concord Ave, Cambridge, MA 02138",
        Capacity: "Capacity: 79",
        Age: "Ages served: 12mo  - 5 years",
        Website: "https://www.cambridgepreschool.org/westcambridge",
        Notes: "Reggio-Emilia, Jewish",
        Hours: "Max Hours: M-F, 8:00am – 6:00pm",
        Enrollment: "Calendar: Academic OR Full-year",
        Cost: "Tuition: Monthly, see website for breakdown based on age",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.1340593, 42.3840483],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Preschool of the Arts - Inman Square",
        Type: "Independent",
        Subtype: "Preschool of the Arts",
        Phone: "617-547-9189",
        Email: "elkie@cambridgepreschool.org",
        Address: "243 Hampshire Street, Cambridge, MA 02139",
        Capacity: "Capacity: 16",
        Age: "Ages served: 6mo  - 4 years",
        Website: "https://www.cambridgepreschool.org/inmansquare",
        Notes: "Reggio-Emilia, Jewish",
        Hours: "Max Hours: M-F, 8:00am – 6:00pm",
        Enrollment: "Calendar: Academic OR Full-year",
        Cost: "Tuition: Monthly, see website for breakdown based on age",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.1010339, 42.3741889],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Panda Bilingual Child Care (East Cambridge)",
        Type: "Independent",
        Subtype: "Panda Bilingual ",
        Phone: "857-957-6800",
        Email: "pandabilingualeast@gmail.com",
        Address: "763 Cambridge Street, Cambridge, MA 02141",
        Capacity: "Capacity: 45",
        Age: "Ages served: 3 mo - 5 yrs",
        Website:
          "http://pandabilingualdaycare.com/default/neiye.html?catid=28&pid=14#",
        Notes: "Montessori, Bilingual (English & Mandarin)",
        Hours: "Max Hours: M-F, 8:00am – 6:00pm",
        Enrollment: "Calendar: Full-year ?",
        Cost: "Tuition: Infant - $2,840/month, Toddler: $2,680/month, Preschool: $2,230/month",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.0894093, 42.3723459],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Panda Bilingual Daycare (North Cambridge)",
        Type: "Independent",
        Subtype: "Panda Bilingual",
        Phone: "857-706-1185",
        Email: "pandabilingual@gmail.com",
        Address: "30 Cambridgepark Drive, Cambridge, MA 02140",
        Capacity: "Capacity: 34",
        Age: "Ages served: 3 mo - 5 yrs",
        Website:
          "http://pandabilingualdaycare.com/default/neiye.html?catid=34&pid=15",
        Notes: "Montessori, Bilingual (English & Mandarin)",
        Hours: "Max Hours: M-F, 8:00am – 6:00pm",
        Enrollment: "Calendar: Full-year ?",
        Cost: "Tuition: Infant - $2,840/month, Toddler: $2,680/month, Preschool: $2,230/month",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.1430877, 42.3937288],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Ecole Francaise - Concord Ave",
        Type: "Independent",
        Subtype: "Ecole Francaise",
        Phone: "339-970-9596",
        Email: "info@efgboston.org",
        Address: "799 Concord Ave, Cambridge, MA 02138",
        Capacity: "",
        Age: "Ages served: 2.9 - 5 yrs",
        Website: "https://www.efgboston.org/schools-and-programs/preschool/",
        Notes: "Bilingual (English & French)",
        Hours: "Max Hours: M-F, 8:30am – 3:00pm",
        Enrollment: "Calendar: Academic",
        Cost: "Tuition: Full week - $15,850/yr (more info on website)",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.1554115, 42.3922433],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Ecole Francaise - Walden Square ",
        Type: "Independent",
        Subtype: "Ecole Francaise",
        Phone: "617-302-6535",
        Email: "herve.seux@efgboston.org",
        Address: "21 Walden Square Road, Cambridge, MA 02140",
        Capacity: "Capacity: 51",
        Age: "Ages served: 21 mo - 5 yrs",
        Website: "https://www.efgboston.org/schools-and-programs/preschool/",
        Notes: "Bilingual (English & French)",
        Hours: "Max Hours: M-F, 8:30am – 3:00pm",
        Enrollment: "Calendar: Academic",
        Cost: "Tuition: Toddler full week - $22,150 (5 days); preK full-week -  $15,850/yr (more info on website)",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.130369, 42.3892646],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Harvard - Botanic Gardens",
        Type: "Independent",
        Subtype: "Harvard",
        Phone: "617-665-5082",
        Email: "bgcc.director@campus-cc.org",
        Address: "26 Robinson Street, Cambridge, MA 02138",
        Capacity: "Capacity: 59",
        Age: "Ages served: 3mo - 5 yrs",
        Website: "https://campuschildcareinc.org/centers/#botanic",
        Notes: "Harvard Affiliated, Play-based",
        Hours: "",
        Enrollment: "Calendar: Academic",
        Cost: "Tuition: Monthly, see website for breakdown based on age",
        Finaid:
          "Tuition assistance info: https://hr.harvard.edu/financial-assistance",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.126603, 42.3831602],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Harvard - Harvard Yard",
        Type: "Independent",
        Subtype: "Harvard",
        Phone: "617-547-3432",
        Email: "hyccc.director@campus-cc.org",
        Address: "25 Francis Ave, Cambridge, MA 02138",
        Capacity: "Capacity: 68",
        Age: "Ages served: 3mo - 5 yrs",
        Website: "https://campuschildcareinc.org/centers/#harvard",
        Notes: "Harvard Affiliated, Play-based",
        Hours: "",
        Enrollment: "Calendar: Full-year",
        Cost: "Tuition: Monthly, see website for breakdown based on age",
        Finaid:
          "Tuition assistance info: https://hr.harvard.edu/financial-assistance",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.1131472, 42.3792116],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Harvard - Oxford Street",
        Type: "Independent",
        Subtype: "Harvard",
        Phone: "617-547-3175",
        Email: "osdc.director@campus-cc.org",
        Address: "25 Francis Ave, Cambridge, MA 02138",
        Capacity: "Capacity: 42",
        Age: "Ages served: 3mo - 5 yrs",
        Website: "https://campuschildcareinc.org/centers/#oxford",
        Notes: "Harvard Affiliated, Play-based",
        Hours: "",
        Enrollment: "Calendar: Full-year",
        Cost: "Tuition: Monthly, see website for breakdown based on age",
        Finaid:
          "Tuition assistance info: https://hr.harvard.edu/financial-assistance",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.1131472, 42.3792116],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Harvard - Radcliffe",
        Type: "Independent",
        Subtype: "Harvard",
        Phone: "617-495-3504",
        Email: "rccc.director@campus-cc.org",
        Address: "10 Dewolf Street, Cambridge, MA 02138",
        Capacity: "Capacity: 60",
        Age: "Ages served: 3mo - 5 yrs",
        Website: "https://campuschildcareinc.org/centers/#radcliffe",
        Notes: "Harvard Affiliated, Play-based",
        Hours: "",
        Enrollment: "Calendar: Full-year",
        Cost: "Tuition: Monthly, see website for breakdown based on age",
        Finaid:
          "Tuition assistance info: https://hr.harvard.edu/financial-assistance",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.1161987, 42.3704272],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Bright Horizons at Biogen Idec",
        Type: "Independent",
        Subtype: "Bright Horizons",
        Phone: "617-621-3383",
        Email: "biogen@brighthorizons.com",
        Address: "300 Binney Street Building #9, Cambridge, MA  02142",
        Capacity: "Capacity: 124",
        Age: "Ages served: infant, toddler, & preschool",
        Website:
          "https://child-care-preschool.brighthorizons.com/MA/Cambridge/biogen",
        Notes: "Only available to families working with Biogen",
        Hours: "Max Hours: M-F, 7:00am – 6:00pm",
        Enrollment: "",
        Cost: "",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.0879394, 42.3660781],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Bright Horizons Childrens Center at Kendall Square",
        Type: "Independent",
        Subtype: "Bright Horizons",
        Phone: "617-577-9532",
        Email: "kendallsquare@brighthorizons.com",
        Address: "286 Cardinal Medeiros Ave, Cambridge, MA 02141",
        Capacity: "Capacity: 97",
        Age: "Ages served: infant, toddler, & preschool",
        Website:
          "https://child-care-preschool.brighthorizons.com/ma/cambridge/kendallsquare",
        Notes: "",
        Hours: "Max Hours: M-F, 7:30am – 5:30pm",
        Enrollment: "",
        Cost: "",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.0900285, 42.3686242],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Bright Horizons at Mass Ave",
        Type: "Independent",
        Subtype: "Bright Horizons",
        Phone: "617-349-3635",
        Email: "massave@brighthorizons.com",
        Address: "2465 Massachusetts Ave, Cambridge, MA 02140",
        Capacity: "Capacity: 113",
        Age: "Ages served: infant, toddler, & preschool",
        Website:
          "https://child-care-preschool.brighthorizons.com/MA/Cambridge/massave",
        Notes: "",
        Hours: "Max Hours: M-F, 7:30am – 5:30pm",
        Enrollment: "",
        Cost: "",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.131534, 42.3987875],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Bright Horizons Children's Center @ University Park",
        Type: "Independent",
        Subtype: "Bright Horizons",
        Phone: "617-621-9553",
        Email: "univ@brighthorizons.com",
        Address: "129 Franklin Street, Cambridge, MA 02139",
        Capacity: "Capacity: 61",
        Age: "Ages served: infant, toddler, & preschool",
        Website:
          "https://child-care-preschool.brighthorizons.com/ma/cambridge/upark",
        Notes: "",
        Hours: "Max Hours: M-F, 7:30am – 5:30pm",
        Enrollment: "",
        Cost: "",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.1014951, 42.3628963],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Technology Childcare Center - Kendall",
        Type: "Independent",
        Subtype: "Bright Horizons",
        Phone: "617-253-5907",
        Email: "doreenan@mit.edu",
        Address: "45 Hayward Street, Cambridge, MA 02142",
        Capacity: "Capacity: 58",
        Age: "Ages served: Infant, toddler, & preschool",
        Website:
          "https://childcare.mit.edu/enrolled-families/kendall-childcare-center",
        Notes: "MIT Affiliated",
        Hours: "Max Hours: M-F, 8:00am ­– 6:00pm",
        Enrollment: "",
        Cost: "Tuition & Scholarship information: https://childcare.mit.edu/tuition-scholarships/tuition-rates",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.0854271, 42.361969],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Technology Childcare Center - Stata",
        Type: "Independent",
        Subtype: "Bright Horizons",
        Phone: "617-253-1305",
        Email: "debradav@mit.edu",
        Address: "32 Vassar Street, Cambridge, MA 02139",
        Capacity: "Capacity: 82",
        Age: "Ages served:",
        Website: "http://childcare.mit.edu/center-locations",
        Notes: "MIT Affiliated",
        Hours: "Max Hours: M-F, 8:00am ­– 6:00pm",
        Enrollment: "",
        Cost: "Tuition & Scholarship information: https://childcare.mit.edu/tuition-scholarships/tuition-rates",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.0906355, 42.3616095],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Technology Childrens Center - North Court",
        Type: "Independent",
        Subtype: "Bright Horizons",
        Phone: "617-253-5907",
        Email: "tcc.eastgate@brighthorizons.com",
        Address: "31 Ames Street, Cambridge, MA 02142",
        Capacity: "Capacity: 7",
        Age: "Ages served:",
        Website: "http://childcare.mit.edu/center-locations",
        Notes: "MIT Affiliated",
        Hours: "",
        Enrollment: "",
        Cost: "Tuition & Scholarship information: https://childcare.mit.edu/tuition-scholarships/tuition-rates",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.0886174, 42.3616931],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Technology Childrens Center - David H. Koch Childcare Center",
        Type: "Independent",
        Subtype: "Bright Horizons",
        Phone: "617-253-4999",
        Email: "tcc.koch@brighthorizons.com",
        Address: "219 Vassar Street, Cambridge, MA 02139",
        Capacity: "Capacity: 126",
        Age: "Ages served: Infant, toddler, & preschool",
        Website: "http://childcare.mit.edu/center-locations",
        Notes: "MIT Affiliated",
        Hours: "Max Hours: M-F, 8:00am ­– 6:00pm",
        Enrollment: "Full-day schedule: 2, 3, or 5 days/week",
        Cost: "Tuition & Scholarship information: https://childcare.mit.edu/tuition-scholarships/tuition-rates",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.1005923, 42.3575859],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Cambridge Nursery School",
        Type: "Independent",
        Subtype: "Independent",
        Phone: "617-547-7288",
        Email: "cambridgenursery@yahoo.com",
        Address: "6 Hillside Place, Cambridge, MA 02140",
        Capacity: "Capacity: 30",
        Age: "Ages served: preschool",
        Website: "http://www.cambridgenurseryschool.org/",
        Notes: "Play-based, Parent Co-op",
        Hours: "Max Hours: M-F, 8:30am ­– 3:00pm",
        Enrollment: "Calendar: Academic",
        Cost: "Tuition: 10,000/yr for morning (additional cost for extended programming)",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.1246362, 42.3861182],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Cambridgeport Children's Center - Tot Lot",
        Type: "Independent",
        Subtype: "Independent",
        Phone: "617-868-4275",
        Email: "carolyn@totlot.org",
        Address: "65R Chestnut Street, Cambridge, MA 02139",
        Capacity: "Capactiy: 35",
        Age: "Ages served: Toddler & preschool",
        Website: "https://www.totlot.org/",
        Notes: "Reggio-Emilia",
        Hours: "Max Hours: M-F, 8:00am - 5:30pm",
        Enrollment: "",
        Cost: "Tuition Information: https://static1.squarespace.com/static/6193bf7a6bb9842e0c96c687/t/6217c10b003fca2c011f3335/1645723915962/2021-2022+tuition.pdf",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.1079381, 42.3566882],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Cambridge Ellis School",
        Type: "Independent",
        Subtype: "Independent",
        Phone: "617-354-0014 x 114",
        Email: "julie@cambridge-ellis.org",
        Address: "80 Trowbridge Street, Cambridge, MA 02138",
        Capacity: "Capacity: 86",
        Age: "Ages served: Toddler & preschool",
        Website: "https://cambridge-ellis.org/",
        Notes: "Play-based",
        Hours: "Max Hours: M-F, 8:30am - 6:00pm",
        Enrollment: "Calendar: Academic",
        Cost: "Tuition: Todder (full-day) $34,572/yr; PreK (full-day) $31,405/yr  (more information @ https://cambridge-ellis.org/admissions/tuition)",
        Finaid:
          "Tuition assistance info: https://cambridge-ellis.org/admissions/financial-aid",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.1095029, 42.3753769],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Cedar Child Care",
        Type: "Independent",
        Subtype: "Independent",
        Phone: "617-818-0781",
        Email: "mycedarchildcare@gmail.com",
        Address: "152-156 Rindge Ave, Cambridge, MA 02140",
        Capacity: "Capacity: 16",
        Age: "Ages served: Infant, toddler, & preschool",
        Website: "https://www.mycedarchildcare.com/",
        Notes: "Reggio-Emilia & Montessori Inspired",
        Hours: "",
        Enrollment: "",
        Cost: "",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.13081, 42.3932541],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Cambridge Montessori",
        Type: "Independent",
        Subtype: "Independent",
        Phone: "617-492-3410",
        Email: "bturner@cambridgemontessori.org",
        Address: "161 Garden Street, Cambridge, MA 02138",
        Capacity: "",
        Age: "Ages served: 21 mo - 5yrs",
        Website: "https://www.cambridgemontessori.org/",
        Notes: "Montessori",
        Hours:
          "Max Hours: (toddler) M-F, 8:30am - 5:30pm, (preK) M-F, 8:30am - 6:00pm",
        Enrollment: "Calendar: Academic",
        Cost: "Tuition: Toddler (full-day) $31,940/yr; PreK (full-day) Tuition: $30,520/yr",
        Finaid:
          "Tuition assistance info: https://www.cambridgemontessori.org/admissions/tuition-and-financial-aid",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.132365, 42.3857824],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Children's Village",
        Type: "Independent",
        Subtype: "Independent",
        Phone: "617-492-1990",
        Email: "childrensvdirector@gmail.com",
        Address: "15 Bay State Road, Cambridge, MA 02138",
        Capacity: "Capacity: 77",
        Age: "Ages served: 10 weeks - 5 yrs",
        Website: "https://www.childrens-village.net/",
        Notes: "Play-based",
        Hours: "Max Hours: M-F, 8:00am - 6:00pm",
        Enrollment: "Calendar: Full-year",
        Cost: "Tuition Info: https://www.childrens-village.net/",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.1406287, 42.3873393],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "East End House, Inc.",
        Type: "Independent",
        Subtype: "Independent",
        Phone: "617-876-4444",
        Email: "camille@eastendhouse.org",
        Address: "105 Spring Street, Cambridge, MA 02141",
        Capacity: "Capacity: 106",
        Age: "Ages served: 15 mo - 5 yrs",
        Website: "https://eastendhouse.org/",
        Notes: "Community-embedded, intergenerational approach",
        Hours: "Max Hours: M-F, 7:30am - 5:30pm",
        Enrollment: "Calendar: Full-year",
        Cost: "Tuition: Toddler - $425/week; PreK - $300/week",
        Finaid:
          "Tuition assistance: financial aid applications & vouchers accepted. More info on website.",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.0830637, 42.3694435],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Evergreen Day School",
        Type: "Independent",
        Subtype: "Independent",
        Phone: "617-492-0090",
        Email: "chris@evergreendayschool.org",
        Address: "795 Concord Ave, Cambridge, MA 02138",
        Capacity: "Capacity: 76",
        Age: "Ages served: 18 mo - 5 yrs",
        Website: "https://www.evergreendayschool.org/",
        Notes: "",
        Hours: "Max Hours: M-F, 8:00am - 4:00pm",
        Enrollment: "Calendar: Academic",
        Cost: "Tuition & Financial Aid Info: https://www.evergreendayschool.org/admissions/",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.155478, 42.391689],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Garden Cooperative Nursery School",
        Type: "Independent",
        Subtype: "Independent",
        Phone: "617-354-4229",
        Email: "office@gardennurseryschool.org",
        Address: "24A Farwell Place, Cambridge, MA 02138",
        Capacity: "Capacity: 18",
        Age: "Ages served: 2.9 - 5 yrs",
        Website: "https://sites.google.com/gardennurseryschool.org/home/",
        Notes: "Part-time, parent/teacher coop. SEL focused.",
        Hours: "Max Hours: M-F, 8:30am - 3:00pm",
        Enrollment: "Caldendar: Academic",
        Cost: "Tuition & Financial Aid Info: https://sites.google.com/gardennurseryschool.org/home/enrollment/tuition-and-fees",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.1206648, 42.3749849],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "The Henry Buckner School",
        Type: "Independent",
        Subtype: "Independent",
        Phone: "617-547-5554",
        Email: "henrybucknerschooldirector@gmail.com",
        Address: "85 Bishop Allen Drive, Cambridge, MA 02139",
        Capacity: "Capacity: 104",
        Age: "Ages served: 3mo - 5 yrs",
        Website: "https://www.henrybucknerschool.org/",
        Notes: 'Uses "Sing, Spell, Read and Write Curriculum"',
        Hours: "Max Hours: M-F, 8:00am - 6:00pm",
        Enrollment: "Calendar: Full-year",
        Cost: "",
        Finaid: "Accepts voucher applicants",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.1016879, 42.3657607],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "The Learning Circle Childcare LLC",
        Type: "Independent",
        Subtype: "Independent",
        Phone: "617-492-6300",
        Email: "ginat@learningcircle.org",
        Address: "657 Cambridge Street, Cambridge, MA 02141",
        Capacity: "Capacity: 24",
        Age: "Ages served: Infant, toddler, & preschool",
        Website: "https://the-learning-circle.org/",
        Notes: "",
        Hours: "Max Hours: M-F, 8:00 am - 5:30 pm",
        Enrollment: "",
        Cost: "",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.0872183, 42.3721443],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Newtowne School Inc.",
        Type: "Independent",
        Subtype: "Independent",
        Phone: "857-829-1014",
        Email: "cmalloy@newtowneschool.org",
        Address: "11 Garden Street, Cambridge, MA 02138",
        Capacity: "Capacity: 56",
        Age: "Ages served: 22 mo - 5 yrs",
        Website: "https://www.newtowneschool.org/",
        Notes: "Reggio-Emilia",
        Hours: "Max Hours: M-F, 8:30am - 3:00pm",
        Enrollment: "Caldendar: Academic",
        Cost: "Tuition & Financial Aid Info: https://www.newtowneschool.org/tuition",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.1229945, 42.3766164],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Parents Nursery School",
        Type: "Independent",
        Subtype: "Independent",
        Phone: "617-864-3913",
        Email: "parentsnurseryschool.director@gmail.com",
        Address: "117 Cushing Street, Cambridge, MA 02138",
        Capacity: "Capacity: 20",
        Age: "Ages served: 2.9 - 5 yrs",
        Website: "https://www.parentsnurseryschool.net/",
        Notes: "Play-based, child-led, parent co-op",
        Hours: "Max Hours: M-F, 8:30am - 3:00pm",
        Enrollment: "Caldendar: Academic",
        Cost: "Tuition & Financial Aid Info: https://www.parentsnurseryschool.net/basic-information/",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.1519533, 42.3781137],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Two Little Owls Schoolhouse",
        Type: "Independent",
        Subtype: "Independent",
        Phone: "617-945-0071",
        Email: "director@twolittleowlsschoolhouse.com",
        Address: "501 Cambridge Street, Cambridge, MA 02141",
        Capacity: "Capacity: 60",
        Age: "Ages served: 8 weeks - 6 years",
        Website: "https://www.twolittleowlsschoolhouse.com/",
        Notes: "",
        Hours: "Max Hours: M-F, 7:30am - 6:00pm",
        Enrollment: "",
        Cost: "Tuition & FInancial Aid Info: https://www.twolittleowlsschoolhouse.com/admissions/enrollment",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.0842718, 42.3717987],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Alef-Bet Child Care Center",
        Type: "Independent",
        Subtype: "Religious",
        Phone: "617-547-3651",
        Email: "alefbetcc.director@gmail.com",
        Address: "8 Tremont Street, Cambridge, MA 02139",
        Capacity: "Capacity: 32",
        Age: "Ages served: 15 mo - 5 yrs",
        Website: "https://www.alefbet-childcare.org/",
        Notes: "Play-based, Jewish School",
        Hours: "Max Hours: M-Th, 8:30am - 5:30pm; F, 8:30am - 3:30pm",
        Enrollment: "Calendar: Full-year",
        Cost: "Tuition: M-F, full day $28,176",
        Finaid:
          "Additional tuition info: https://www.alefbet-childcare.org/program",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.0993161, 42.3693237],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Malik Academy/Al Bustan Preschool",
        Type: "Independent",
        Subtype: "Religious",
        Phone: "617-868-2322",
        Email: "director@malikacademy.org",
        Address: "808 Memorial Drive, Cambridge, MA 02139",
        Capacity: "Capacity: 53",
        Age: "Ages served: Toddler & preschool",
        Website: "https://www.malikacademy.org/pre-school/",
        Notes: "Child-centered, Islamic Education",
        Hours: "",
        Enrollment: "",
        Cost: "Tuition Info: https://www.malikacademy.org/pre-school/",
        Finaid:
          "Tuition assistance info: https://www.malikacademy.org/financial-aid/",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.1153677, 42.3607318],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Little Folks Fellowship Nursery School",
        Type: "Independent",
        Subtype: "Religious",
        Phone: "617-868-4285",
        Email: "littlefolksfellowshipns@yahoo.com",
        Address: "1418 Cambridge Street, Cambridge, MA 02139",
        Capacity: "Capacity: 20",
        Age: "Ages served: toddlers, preschool, & kindergarten",
        Website:
          "https://www.fupc-cambridge.org/little-folks-fellowship-nursery-sch",
        Notes: "Christian",
        Hours: "Max Hours: M-W-F, 8:30am - 2pm",
        Enrollment: "Calendar: Academic",
        Cost: "Tuition Info: $440 per month (8:30am - 12pm session); $620/month (8:30am - 2pm session)",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.101924, 42.3735609],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "KinderCare - Cambridge",
        Type: "Independent",
        Subtype: "Network",
        Phone: "617-876-0102",
        Email: "vfreeman@kindercare.com",
        Address: "100 Cambridgepark Drive, Cambridge, MA 02140",
        Capacity: "Capacity: 78",
        Age: "Ages served: 6 wks - 6 yrs",
        Website: "https://www.kindercare.com/our-centers/cambridge/ma/301902",
        Notes: "",
        Hours: "Max Hours: M-F, 6:00am - 6:00pm",
        Enrollment: "",
        Cost: "Tuition info: https://www.kindercare.com/resources/child-care-costs",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.1448349, 42.3942731],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Kiddie Academy of Cambridge",
        Type: "Independent",
        Subtype: "Network",
        Phone: "617-945-0021",
        Email: "cambridge@kiddieacademy.net",
        Address: "299 Prospect Street, Cambridge, MA 02139",
        Capacity: "Capacity: 119",
        Age: "Ages served: Infant, toddler, & preschool",
        Website: "https://kiddieacademy.com/academies/cambridge/",
        Notes: "",
        Hours: "",
        Enrollment: "",
        Cost: "",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.0989418, 42.3728162],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Nurtury Inc. @ Harvard Street",
        Type: "Independent",
        Subtype: "Network",
        Phone: "617-492-3935",
        Email: "sjohnson@nurturyboston.org",
        Address: "243 Harvard Street, Cambridge, MA 02139",
        Capacity: "Capacity: 66",
        Age: "Ages served: Infant, toddler, & preschool",
        Website:
          "https://www.nurturyboston.org/what-we-do/locations/243-harvard-street",
        Notes: "",
        Hours: "Max Hours: M-F, 7:30am - 5:00pm",
        Enrollment: "Calendar: Full-year",
        Cost: "Enrollment & tuition info: https://www.nurturyboston.org/what-we-do/enrollment",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.1009817, 42.3682726],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Cambridge Our Place",
        Type: "Independent",
        Subtype: "Network",
        Phone: "617-547-3400 x 237",
        Email: "akilah.cooper@use.salvationarmy.org",
        Address: "402 Massachusetts Ave, Cambridge, MA 02139",
        Capacity: "Capacity: 44",
        Age: "Ages served: Infant, toddler, & preschool",
        Website: "https://massachusetts.salvationarmy.org/MA/OurPlace",
        Notes: "",
        Hours: "",
        Enrollment: "",
        Cost: "",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.1005202, 42.3630642],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Pine Village Preschool - Porter",
        Type: "Independent",
        Subtype: "Pine Village",
        Phone: "617-547-4700",
        Email: "porter@pinevillagepreschool.com",
        Address: "2067 Massachusetts Ave, Cambridge, MA 02140",
        Capacity: "Capacity: 48",
        Age: "Ages served: 15 mo - 6 yrs",
        Website: "https://pinevillagepreschool.com/locations/porter-square/",
        Notes: "Bilingual (English & Spanish)",
        Hours: "Max Hours: M-F, 8:00am - 5:30pm",
        Enrollment: "Calendar: Academic",
        Cost: "",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.1228954, 42.3915915],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Pine Village Preschool - Kendall",
        Type: "Independent",
        Subtype: "Pine Village",
        Phone: "508-212-7486",
        Email: "kspinevillage@gmail.com",
        Address: "695 W Kendall Street, Cambridge, MA 02142",
        Capacity: "Capacity: 56",
        Age: "Ages served: 15 mo - 6 yrs",
        Website: "https://pinevillagepreschool.com/locations/kendall-square/",
        Notes: "Bilingual (English & Spanish)",
        Hours: "Max Hours: M-F, 8:00am - 5:30pm",
        Enrollment: "Calendar: Academic",
        Cost: "",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.0820557, 42.3648716],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Sunrise Learning Academy 2, LLC",
        Type: "Independent",
        Subtype: "Network",
        Phone: "617-868-0077",
        Email: "directoralewife@sunriselearningacademy.com",
        Address: "7 Cambridgepark Drive, Cambridge, MA 02140",
        Capacity: "Capacity: 117",
        Age: "Ages served: 8 wks - 5 yrs",
        Website: "https://sunriselearningacademy.com/",
        Notes: "",
        Hours: "",
        Enrollment: "",
        Cost: "",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.1422291, 42.394962],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Cambridge Family YMCA - A Child's Place",
        Type: "Independent",
        Subtype: "Network",
        Phone: "617-661-9622",
        Email: "preschool@cambymca.org",
        Address: "820 Massachusetts Ave, Cambridge, MA 02139",
        Capacity: "Capacity: 82",
        Age: "Ages served: 2.9 - 5 yrs",
        Website: "https://www.cambridgeymca.org/childcare/preschool/",
        Notes: "",
        Hours: "Max Hours: M-F, 8:00am - 5:30pm",
        Enrollment: "",
        Cost: "Tuition: Half Days (8:00am - 12:00pm) - $750/month; Full Days (8:00am - 5:30pm) - $1450/month",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.1067528, 42.3668823],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Artisan Child Care Center",
        Type: "Independent",
        Subtype: "Network",
        Phone: "617-583-0767",
        Email: "melissa@artisanchildcare.com",
        Address: "151 Alewife Parkway, Cambridge, MA 02140",
        Capacity: "Capacity: 16",
        Age: "Ages served: 6 wks - 5 yrs",
        Website: "https://www.artisanchildcare.com/",
        Notes: "Music curriculum",
        Hours: "Max Hours: M-F, 7:30am - 6:00pm",
        Enrollment: "",
        Cost: "",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.1410404, 42.3934716],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Windsor Preschool (DHSP)",
        Type: "Public",
        Subtype: "DHSP",
        Phone: "617-349-9456",
        Email: "meghanm@cambridgema.gov",
        Address: "119 Windsor Street, Cambridge, MA 02139",
        Capacity: "Capacity: 34",
        Age: "Ages served:",
        Website:
          "https://www.cambridgema.gov/dhsp/programsforkidsandyouth/preschool/windsorpreschool",
        Notes: "",
        Hours: "",
        Enrollment: "",
        Cost: "",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.0966704, 42.3647468],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Peabody Preschool (DHSP)",
        Type: "Public",
        Subtype: "DHSP",
        Phone: "617-349-6275",
        Email: "meghanm@cambridgema.gov",
        Address: "70 Rindge Ave, Cambridge, MA 02140",
        Capacity: "Capacity: 65",
        Age: "Ages served:",
        Website:
          "https://www.cambridgema.gov/DHSP/programsforkidsandyouth/Preschool/peabodypreschool",
        Notes: "",
        Hours: "",
        Enrollment: "",
        Cost: "",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.1282179, 42.3922586],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Morse Preschool (DHSP)",
        Type: "Public",
        Subtype: "DHSP",
        Phone: "617-349-4485",
        Email: "meghanm@cambridgema.gov",
        Address: "40 Granite Street, Cambridge, MA 02139",
        Capacity: "Capacity: 61",
        Age: "Ages served:",
        Website:
          "https://www.cambridgema.gov/DHSP/programsforkidsandyouth/Preschool/morsepreschool",
        Notes: "",
        Hours: "",
        Enrollment: "",
        Cost: "",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.1115008, 42.355487],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Kennedy-Longfellow Preschool (DHSP)",
        Type: "Public",
        Subtype: "DHSP",
        Phone: "617-349-4484",
        Email: "meghanm@cambridgema.gov",
        Address: "158 Spring Street, Cambridge, MA 02141",
        Capacity: "Capacity: 20",
        Age: "Ages served:",
        Website:
          "https://www.cambridgema.gov/DHSP/programsforkidsandyouth/Preschool/kennedylongfellowpreschool",
        Notes: "",
        Hours: "",
        Enrollment: "",
        Cost: "",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.0871966, 42.3695143],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Haggerty Preschool (DHSP)",
        Type: "Public",
        Subtype: "DHSP",
        Phone: "617-349-6265",
        Email: "meghanm@cambridgema.gov",
        Address: "110 Cushing Street, Cambridge, MA 02138",
        Capacity: "Capacity: 16",
        Age: "Ages served:",
        Website:
          "https://www.cambridgema.gov/DHSP/programsforkidsandyouth/Preschool/haggertypreschool",
        Notes: "",
        Hours: "",
        Enrollment: "",
        Cost: "",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.1525569, 42.3781199],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "King Open Preschool (DHSP)",
        Type: "Public",
        Subtype: "DHSP",
        Phone: "617-349-6261",
        Email: "meghanm@cambridgema.gov",
        Address: "101 Willow Street, Cambridge, MA 02141 02141",
        Capacity: "Capacity: 34",
        Age: "Ages served:",
        Website:
          "https://www.cambridgema.gov/DHSP/programsforkidsandyouth/Preschool/kingopenpreschool",
        Notes: "",
        Hours: "",
        Enrollment: "",
        Cost: "",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.0918275, 42.372549],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Martin Luther King Preschool (DHSP)",
        Type: "Public",
        Subtype: "DHSP",
        Phone: "617-349-6270",
        Email: "meghanm@cambridgema.gov",
        Address: "100 Putnam Ave, Cambridge, MA 02139",
        Capacity: "Capacity: 86",
        Age: "Ages served:",
        Website:
          "https://www.cambridgema.gov/DHSP/programsforkidsandyouth/Preschool/martinlutherkingjrpreschool",
        Notes: "",
        Hours: "",
        Enrollment: "",
        Cost: "",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.113648, 42.3659079],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "CAAS Head Start- Frisoli Center",
        Type: "Head Start",
        Subtype: "Head Start",
        Phone: "617-623-7370",
        Email: "jleonard@caasomerville.org",
        Address: "61 Willow Street, Cambridge, MA 02141",
        Capacity: "Capacity: 39",
        Age: "Ages served:",
        Website:
          "https://www.finditcambridge.org/programs/caas-head-start-frisoli-center",
        Notes: "",
        Hours: "",
        Enrollment: "",
        Cost: "",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.0922568, 42.3710826],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "CAAS Head Start/ Jefferson Park ",
        Type: "Head Start",
        Subtype: "Head Start",
        Phone: "617-623-7370",
        Email: "jleonard@caasomerville.org",
        Address: "280 Rindge Ave, Cambridge, MA 02140",
        Capacity: "Capacity: 36",
        Age: "Ages served:",
        Website:
          "https://www.finditcambridge.org/programs/caas-head-start-jefferson-park",
        Notes: "",
        Hours: "",
        Enrollment: "",
        Cost: "",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.1353762, 42.393505],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Fletcher-Maynard Academy Scholar College",
        Type: "Public",
        Subtype: "CPS",
        Phone: "617-349-4395",
        Email: "mrounds@cpsd.us",
        Address: "225 Windsor Street, Cambridge, MA 02139",
        Capacity: "Capacity: 20",
        Age: "Ages served:",
        Website:
          "https://www.cpsd.us/departments/src/registering_for/new_3_year_old_lottery/fletcher_maynard_academy_scholar_college",
        Notes: "",
        Hours: "",
        Enrollment: "",
        Cost: "",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.0959372, 42.3668508],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Tobin Montessori Children's House",
        Type: "Public",
        Subtype: "CPS",
        Phone: "617-349-6600",
        Email: "jfrost@cpsd.us",
        Address: "359 Broadway, Cambridge, MA 02139",
        Capacity: "Capacity: 40",
        Age: "Ages served:",
        Website: "https://tobin.cpsd.us/about_our_school",
        Notes: "",
        Hours: "",
        Enrollment: "",
        Cost: "",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.1038626, 42.3709829],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Baldwin (Special Start)",
        Type: "Public",
        Subtype: "CPS",
        Phone: "617-349-6502",
        Email: "skellywalker@cpsd.us",
        Address: "85 Oxford Street, Cambridge, MA 02138",
        Capacity: "Capacity: 15",
        Age: "Ages served:",
        Website: "",
        Notes: "Special Needs",
        Hours: "",
        Enrollment: "",
        Cost: "",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.1168143, 42.3823558],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Cambridgeport (Special Start)",
        Type: "Public",
        Subtype: "CPS",
        Phone: "617-349-6502",
        Email: "skellywalker@cpsd.us",
        Address: "89 Elm Street, Cambridge, MA 02139",
        Capacity: "Capacity: 36",
        Age: "Ages served:",
        Website: "",
        Notes: "Special Needs",
        Hours: "",
        Enrollment: "",
        Cost: "",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.0978307, 42.3693687],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Graham & Parks (Special Start)",
        Type: "Public",
        Subtype: "CPS",
        Phone: "617-349-6502",
        Email: "skellywalker@cpsd.us",
        Address: "44 Linnaean Street, Cambridge, MA 02138",
        Capacity: "Capacity: 14",
        Age: "Ages served:",
        Website: "",
        Notes: "Special Needs",
        Hours: "",
        Enrollment: "",
        Cost: "",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.1236381, 42.3828869],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Kennedy-Longfellow (Special Start)",
        Type: "Public",
        Subtype: "CPS",
        Phone: "617-349-6502",
        Email: "skellywalker@cpsd.us",
        Address: "158 Spring Street, Cambridge, MA 02141",
        Capacity: "Capacity: 0",
        Age: "Ages served:",
        Website: "",
        Notes: "Special Needs",
        Hours: "",
        Enrollment: "",
        Cost: "",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.0871966, 42.3695143],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Morse (Special Start)",
        Type: "Public",
        Subtype: "CPS",
        Phone: "617-349-6502",
        Email: "skellywalker@cpsd.us",
        Address: "40 Granite Street, Cambridge, MA 02139",
        Capacity: "Capacity: 50",
        Age: "Ages served:",
        Website: "",
        Notes: "Special Needs",
        Hours: "",
        Enrollment: "",
        Cost: "",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.1115008, 42.355487],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Peabody (Special Start)",
        Type: "Public",
        Subtype: "CPS",
        Phone: "617-349-6502",
        Email: "skellywalker@cpsd.us",
        Address: "70 Rindge Ave, Cambridge, MA 02140",
        Capacity: "Capacity: 21",
        Age: "Ages served:",
        Website: "",
        Notes: "Special Needs",
        Hours: "",
        Enrollment: "",
        Cost: "",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.1282179, 42.3922586],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Tobin (Special Start)",
        Type: "Public",
        Subtype: "CPS",
        Phone: "617-349-6502",
        Email: "skellywalker@cpsd.us",
        Address: "359 Broadway, Cambridge, MA 02139",
        Capacity: "Capacity: 65",
        Age: "Ages served:",
        Website: "",
        Notes: "Special Needs",
        Hours: "",
        Enrollment: "",
        Cost: "",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.1038626, 42.3709829],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Allen, Judy",
        Type: "Family Child Care",
        Subtype: "",
        Phone: "857-417-5124",
        Email: "judy4915@yahoo.com",
        Address: "5 Clifton Circle, Apt 523, Cambridge, MA 02140",
        Capacity: "Capacity: 4",
        Age: "",
        Website: "",
        Notes: "",
        Hours: "",
        Enrollment: "",
        Cost: "",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.1367985, 42.3929477],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Barnes, Winsome",
        Type: "Family Child Care",
        Subtype: "",
        Phone: "617-491-2451",
        Email: "winsomeredd@yahoo.com",
        Address: "153 Allston Street Apt 2, Cambridge, MA 02139",
        Capacity: "Capacity: 6",
        Age: "",
        Website: "",
        Notes: "",
        Hours: "",
        Enrollment: "",
        Cost: "",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.1079734, 42.3587265],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Calle, Reina",
        Type: "Family Child Care",
        Subtype: "",
        Phone: "617-441-9334",
        Email: "reinacalle3@hotmail.com",
        Address: "1 Woodrow Wilson Court Apt 2, Cambridge, MA 02139",
        Capacity: "Capacity: 8",
        Age: "",
        Website: "",
        Notes: "",
        Hours: "",
        Enrollment: "",
        Cost: "",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.1092224, 42.3614006],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Clarke, Laura",
        Type: "Family Child Care",
        Subtype: "",
        Phone: "617-735-5116",
        Email: "lsbckbl@yahoo.com",
        Address: "129 Franklin Street #133, Cambridge, MA 02139",
        Capacity: "Capacity: 6",
        Age: "",
        Website: "",
        Notes: "",
        Hours: "",
        Enrollment: "",
        Cost: "",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.1011123, 42.362606],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Dejesus-Acevedo, Jennie",
        Type: "Family Child Care",
        Subtype: "",
        Phone: "857-999-5442",
        Email: "jnnace0213@yahoo.com",
        Address: "3 Palermo Street #1, Cambridge, MA 02141",
        Capacity: "Capacity: 10",
        Age: "",
        Website: "",
        Notes: "",
        Hours: "",
        Enrollment: "",
        Cost: "",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.0925648, 42.3719088],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Fatima, Kaniz",
        Type: "Family Child Care",
        Subtype: "",
        Phone: "617-386-3770",
        Email: "keejala@yahoo.com",
        Address: "113 Richdale Avenue #24, Cambridge, MA 02140",
        Capacity: "Capacity: 6",
        Age: "",
        Website: "",
        Notes: "",
        Hours: "",
        Enrollment: "",
        Cost: "",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.125282, 42.3892013],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Greaves, Cynthia",
        Type: "Family Child Care",
        Subtype: "",
        Phone: "617-497-5314",
        Email: "ramsaran@comcast.net",
        Address: "24 Jay Street, Cambridge, MA 02139",
        Capacity: "Capacity: 8",
        Age: "",
        Website: "",
        Notes: "",
        Hours: "",
        Enrollment: "",
        Cost: "",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.1097357, 42.3651745],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Holder, Dian",
        Type: "Family Child Care",
        Subtype: "",
        Phone: "617-945-1250",
        Email: "dinaholder@comcast.net",
        Address: "7 Lincon Way, Cambridge, MA 02140",
        Capacity: "Capacity: 6",
        Age: "",
        Website: "",
        Notes: "",
        Hours: "",
        Enrollment: "",
        Cost: "",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.1286087, 42.3873054],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Perez, Rosa",
        Type: "Family Child Care",
        Subtype: "",
        Phone: "857-242-9223",
        Email: "perezrosa285@gmail.com",
        Address: "315 Evereteze Way, Cambridge, MA 02141",
        Capacity: "Capacity: 6",
        Age: "",
        Website: "",
        Notes: "",
        Hours: "",
        Enrollment: "",
        Cost: "",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.0926682, 42.3734196],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Simpson, Lillian",
        Type: "Family Child Care",
        Subtype: "",
        Phone: "617-576-0871",
        Email: "smileyhearts@comcast.net",
        Address: "2 Frances Place, Cambridge, MA 02140",
        Capacity: "Capacity: 6",
        Age: "",
        Website: "",
        Notes: "",
        Hours: "",
        Enrollment: "",
        Cost: "",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.1334965, 42.3943541],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Smith, Christina",
        Type: "Family Child Care",
        Subtype: "",
        Phone: "857-829-4097",
        Email: "c_a_smith@comcast.net",
        Address: "14 Carlisle Street, Cambridge, MA 02139",
        Capacity: "Capacity: 6",
        Age: "",
        Website: "",
        Notes: "",
        Hours: "",
        Enrollment: "",
        Cost: "",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.0982778, 42.3722859],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Thomas, Sarah",
        Type: "Family Child Care",
        Subtype: "",
        Phone: "617-945-9588",
        Email: "sarahthomas203",
        Address: "203 Prospect Street, Cambridge, MA 02139",
        Capacity: "",
        Age: "",
        Website: "",
        Notes: "",
        Hours: "",
        Enrollment: "",
        Cost: "",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.1008181, 42.3705326],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Torres, Maria C.",
        Type: "Family Child Care",
        Subtype: "",
        Phone: "857-251-2699",
        Email: "mariatorresclc@yahoo.com",
        Address: "398 Evereteze Way, Cambridge, MA 02141",
        Capacity: "Capacity: 6",
        Age: "",
        Website: "",
        Notes: "",
        Hours: "",
        Enrollment: "",
        Cost: "",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.0922893, 42.3735708],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Winston, Emily",
        Type: "Family Child Care",
        Subtype: "",
        Phone: "617-548-5658",
        Email: "heyitsemily@gmail.com",
        Address: "22 Beech Street, Cambridge, MA 02140",
        Capacity: "Capacity: 6",
        Age: "",
        Website: "",
        Notes: "",
        Hours: "",
        Enrollment: "",
        Cost: "",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.1190309, 42.3911468],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Yudon, Tsering",
        Type: "Family Child Care",
        Subtype: "",
        Phone: "617-661-1986",
        Email: "tseyou74@yahoo.com",
        Address: "63 Cedar Street, Cambridge, MA 02140",
        Capacity: "Capacity: 10",
        Age: "",
        Website: "",
        Notes: "",
        Hours: "",
        Enrollment: "",
        Cost: "",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.13099, 42.3939217],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Zarchi, Elka",
        Type: "Family Child Care",
        Subtype: "",
        Phone: "617-834-5407",
        Email: "elkiezarchi@gmail.com",
        Address: "54 Banks Street, Cambridge, MA 02138",
        Capacity: "Capacity: 10",
        Age: "",
        Website: "",
        Notes: "",
        Hours: "",
        Enrollment: "",
        Cost: "",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.1144707, 42.3692831],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Buckingham Browne & Nichols Lower School",
        Type: "Independent",
        Subtype: "",
        Phone: "617-800-2461",
        Email: "areppucci@bbns.org",
        Address: "10 Buckingham Pl, Cambridge, MA 02138",
        Capacity: "",
        Age: "Ages served:",
        Website: "",
        Notes: "",
        Hours: "",
        Enrollment: "",
        Cost: "",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.1285727, 42.3791821],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Fayerweather Street School",
        Type: "Independent",
        Subtype: "",
        Phone: "617-876-4746",
        Email: "kridley@fayerweather.org",
        Address: "765 Concord Avenue, Cambridge, MA 02138",
        Capacity: "",
        Age: "Ages served: 3-5 yrs",
        Website: "https://www.fayerweather.org/",
        Notes: "",
        Hours: "Max Hours: 8:30am - 3:15pm",
        Enrollment: "Calendar: Academic",
        Cost: "Full-day (M-F): $29,450",
        Finaid:
          "Tuition assistance info: https://www.fayerweather.org/admission/tuition-and-tuition-assistance",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.1542357, 42.3913269],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Cambridge Friends School",
        Type: "Independent",
        Subtype: "",
        Phone: "617-354-3880",
        Email: "k.marion@cambridgefriendsschool.org",
        Address: "5 Cadbury Road, Cambridge, MA 02140",
        Capacity: "",
        Age: "Ages served:",
        Website: "https://cambridgefriendsschool.org/",
        Notes: "",
        Hours: "",
        Enrollment: "Calendar: Academic",
        Cost: "Full-day (M-F): $28,212",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.130835, 42.3879342],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "Shady Hill School",
        Type: "Independent",
        Subtype: "",
        Phone: "617-520-5260",
        Email: "shalini.rao@shs.org",
        Address: "178 Coolidge Hill, Cambridge MA, 02138",
        Capacity: "",
        Age: "Ages served: 4-5 yrs",
        Website: "https://www.shs.org/",
        Notes: "",
        Hours: "",
        Enrollment: "Calendar: Academic",
        Cost: "Tuition & Tuition Assistance Info: https://www.shs.org/apply/tuition--financial-aid ",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.137796, 42.3709334],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "St. Peter's School",
        Type: "Independent",
        Subtype: "",
        Phone: "617-547-0101",
        Email: "admin@saint-peter-school.org",
        Address: "96 Concord Ave, Cambridge, MA 02138",
        Capacity: "",
        Age: "Ages served:",
        Website: "https://saint-peter-school.org/",
        Notes: "Religious (Catholic)",
        Hours: "",
        Enrollment: "Calendar: Academic",
        Cost: "Annual Tuition: $9,974",
        Finaid: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.1295934, 42.3810889],
      },
    },
    {
      type: "Feature",
      properties: {
        Name: "International School of Boston",
        Type: "Independent",
        Subtype: "",
        Phone: "617-499-1451",
        Email: "contact@isbos.org",
        Address: "45 Matignon Road, Cambridge, MA 02140",
        Capacity: "",
        Age: "Ages served:",
        Website: "",
        Notes: "Bilingual (English & French)",
        Hours: "",
        Enrollment: "",
        Cost: "",
      },
      geometry: {
        type: "Point",
        coordinates: [-71.1331077, 42.4024561],
      },
    },
  ],
};
